# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "bootstrap.sh"

  config.vm.define "elk-server" do |server|
    server.vm.box = "centos/7"
    server.vm.hostname = "elk-server.hspace.com"
    server.vm.network "private_network", ip: "172.42.42.10"
    server.vm.provider "virtualbox" do |vb|
      vb.name = "elk-server"
      vb.memory = 1024
      vb.cpus = 1
    end
  end

  config.vm.define "elk-client" do |client|
    client.vm.box = "centos/7"
    client.vm.hostname = "elk-client.hspace.com"
    client.vm.network "private_network", ip: "172.42.42.20"
    client.vm.provider "virtualbox" do |vb|
      vb.name = "elk-client"
      vb.memory = 512
      vb.cpus = 1
    end
  end

end
